/**
 ******************************************************************************
 * @file           : ssd1306_defines.c
 * @brief          : SSD1306 Settings
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 Lars Boegild Thomsen <lbthomsen@gmail.com>
 * Copyright (c) 2019 Andriy Honcharenko
 * Copyright (c) 2021 Roberto Benjami
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef SSD1306_DEFINES_H_
#define SSD1306_DEFINES_H_

#define SSD1306_I2C_PORT  hi2c1   // I2C port as defined in main generated by CubeMx (hi2c1 or hi2c2 or hi2c3)
#define SSD1306_ADDRESS    0x3C   // I2C address display
#define SSD1306_128X64            // SSD1306_128X32 or SSD1306_128X64
#define SSD1306_USE_DMA       1   // 0: not used I2C DMA mode, 1: used I2C DMA mode
#define SSD1306_CONTUPDATE    0   // 0: continue update mode disable, 1: continue update mode enable (only DMA MODE)
#define SSD1306_X_OFFSET      2   // My device require this - no idea why

#endif /* SSD1306_DEFINES_H_ */
